-- Migration: Fix Row Level Security (RLS) policies for full CRUD access
-- Enables seamless demo & production CRUD operations on all tables

-- 1. KEPALA_KELUARGA
DROP POLICY IF EXISTS "SEKRETARIS can CRUD KEPALA_KELUARGA" ON KEPALA_KELUARGA;
DROP POLICY IF EXISTS "BENDAHARA can view KEPALA_KELUARGA" ON KEPALA_KELUARGA;
DROP POLICY IF EXISTS "PAROKI can view KEPALA_KELUARGA" ON KEPALA_KELUARGA;
DROP POLICY IF EXISTS "Enable all access for KEPALA_KELUARGA" ON KEPALA_KELUARGA;

CREATE POLICY "Enable all access for KEPALA_KELUARGA" ON KEPALA_KELUARGA
FOR ALL USING (true) WITH CHECK (true);

-- 2. JURNAL_TRANSAKSI
DROP POLICY IF EXISTS "BENDAHARA can CRUD JURNAL_TRANSAKSI" ON JURNAL_TRANSAKSI;
DROP POLICY IF EXISTS "SEKRETARIS can view JURNAL_TRANSAKSI" ON JURNAL_TRANSAKSI;
DROP POLICY IF EXISTS "PAROKI can view JURNAL_TRANSAKSI" ON JURNAL_TRANSAKSI;
DROP POLICY IF EXISTS "Enable all access for JURNAL_TRANSAKSI" ON JURNAL_TRANSAKSI;

CREATE POLICY "Enable all access for JURNAL_TRANSAKSI" ON JURNAL_TRANSAKSI
FOR ALL USING (true) WITH CHECK (true);

-- 3. ASET
DROP POLICY IF EXISTS "BENDAHARA can CRUD ASET" ON ASET;
DROP POLICY IF EXISTS "SEKRETARIS can view ASET" ON ASET;
DROP POLICY IF EXISTS "PAROKI can view ASET" ON ASET;
DROP POLICY IF EXISTS "Enable all access for ASET" ON ASET;

CREATE POLICY "Enable all access for ASET" ON ASET
FOR ALL USING (true) WITH CHECK (true);

-- 4. PROFIL_LINGKUNGAN
DROP POLICY IF EXISTS "SEKRETARIS and BENDAHARA can update PROFIL_LINGKUNGAN" ON PROFIL_LINGKUNGAN;
DROP POLICY IF EXISTS "SEKRETARIS, BENDAHARA, PAROKI can view PROFIL_LINGKUNGAN" ON PROFIL_LINGKUNGAN;
DROP POLICY IF EXISTS "Enable all access for PROFIL_LINGKUNGAN" ON PROFIL_LINGKUNGAN;

CREATE POLICY "Enable all access for PROFIL_LINGKUNGAN" ON PROFIL_LINGKUNGAN
FOR ALL USING (true) WITH CHECK (true);

-- 5. USERS
DROP POLICY IF EXISTS "Users can read own profile" ON USERS;
DROP POLICY IF EXISTS "Enable all access for USERS" ON USERS;

CREATE POLICY "Enable all access for USERS" ON USERS
FOR ALL USING (true) WITH CHECK (true);

-- 6. LINGKUNGAN & COA
DROP POLICY IF EXISTS "All users can read LINGKUNGAN" ON LINGKUNGAN;
CREATE POLICY "Enable all access for LINGKUNGAN" ON LINGKUNGAN
FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "All users can read COA" ON COA;
CREATE POLICY "Enable all access for COA" ON COA
FOR ALL USING (true) WITH CHECK (true);
